version: '3'

services:
  dev:
    image: node:19
    user: node
    working_dir: /usr/src/full_stack_open/
    volumes:
      - .:/usr/src/full_stack_open/
    ports:
      - 3000:3000
    environment:
      - REACT_APP_APIKEY=PUT_KEY_HERE
    command: npm run --prefix /usr/src/full_stack_open/part2/countries start

  db:
    image: node:19
    user: node
    working_dir: /usr/src/full_stack_open/
    volumes:
      - .:/usr/src/full_stack_open/
    ports:
      - 3001:3001
    command: npx json-server --host 0.0.0.0 --port 3001 --watch db.json 
